
REGISTER_STATES=["GET_STUDENT_ID","TEAM_CHECKED"]
ASSISTANT_STATES=["GET_STUDENT_ID","ID_CHECKED"]
CHECK_STATES =["GET_STUDENT_ID","SELECT_BUTTON","SCORE_CHECKED","ATENDACNE_CHECKED","SCORE_SELECT"]
GROUP_STATE = ["GET_STUDENT_ID","GET_CLASS_CODE"]